Meeting Minutes/Meeting Minutes/Models/ErrorViewModel.cs
namespace Meeting_Minutes.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Meeting Minutes/Meeting Minutes/Models/Item.cs
using System.ComponentModel.DataAnnotations;

namespace Meeting_Minutes.Models
{
    public class Item
    {
        [Key]
        public int itemId { get; set; }

        public string ItemName { get; set; }

        public string ItemDescription { get; set; }

        public DateTime DueDate { get; set; }

        public string CurrentStatus { get; set; }

        //Relationships

        public List<Meetings_Items> Meeting_Item { get; set; }

        public List<ItemStatus> ItemStatus { get; set; }

        //User

        public int UserId { get; set; }
        public User User { get; set; }  
    }
}

Meeting Minutes/Meeting Minutes/Models/ItemStatus.cs
using System.ComponentModel.DataAnnotations;

namespace Meeting_Minutes.Models
{
    public class ItemStatus
    {
        [Key]
        public int StatusId { get; set; }

        public string Status { get; set; }

        public DateTime StatusDate { get; set; }

        //Relationships

        public int itemId { get; set; }
        public Item item { get; set; }

    }
}

Meeting Minutes/Meeting Minutes/Models/Meeting.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Meeting_Minutes.Models
{
    public class Meeting
    {
        [Key]
        public int meetingID { get; set; }

        public int meetingNumber { get; set; }

        public DateTime meetingDate { get; set; }

        //Meeting Types

        public int MeetingTypeId { get; set; }
        [ForeignKey("MeetingTypeId")]
        public MeetingTypes meetingType { get; set; }

        //Relationships
        public List<Meetings_Items> Meeting_Item { get; set; }

       
    }
}

Meeting Minutes/Meeting Minutes/Models/MeetingTypes.cs
using System.ComponentModel.DataAnnotations;

namespace Meeting_Minutes.Models
{
    public class MeetingTypes
    {
        [Key]
        public int MeetingTypeId { get; set; }
        public string Name { get; set; }

        //Relationships

        public List<Meeting> Meeting { get; set; }


       
    }
}

Meeting Minutes/Meeting Minutes/Models/Meetings_Items.cs
namespace Meeting_Minutes.Models
{
    public class Meetings_Items
    {
        public int meetingId { get; set; }
        public Meeting Meeting { get; set; }

        public int itemId { get; set; }
        public Item Item { get; set; }
    }
}

Meeting Minutes/Meeting Minutes/Models/User.cs
using System.ComponentModel.DataAnnotations;

namespace Meeting_Minutes.Models
{
    public class User
    {
        [Key]
        public int UserId { get; set; }

        public string UserName { get; set; }

        //Relationships
        public List<Item> Items { get; set; }

        
    }
}

Meeting Minutes/Meeting Minutes/Controllers/HomeController.cs
using Meeting_Minutes.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Meeting_Minutes.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Meeting Minutes/Meeting Minutes/Controllers/MeetingController.cs
using Meeting_Minutes.Data;
using Meeting_Minutes.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;


namespace Meeting_Minutes.Controllers
{
    public class MeetingController : Controller
    {
        [HttpGet]
        //GET : MEETS
        public IActionResult Index()
        {
           List<Meeting> meet = new List<Meeting>();
           DataAccess dataAccess = new DataAccess();
           meet = dataAccess.FetchAllMeets();

           return View("Index", meet);
        }

    }

  
}

Meeting Minutes/Meeting Minutes/Controllers/UserController.cs
using Meeting_Minutes.Data;
using Meeting_Minutes.Models;
using Microsoft.AspNetCore.Mvc;

namespace Meeting_Minutes.Controllers
{
    public class UserController : Controller
    {
        [HttpGet]
        //GET : USERS
        public IActionResult Index()
        {
            List<User> user = new List<User>();
            DataAccess dataAccess = new DataAccess();

            user = dataAccess.FetchAllUser();

            return View("Index", user);
        }

        public IActionResult DeleteUser(int id)
        {
            DataAccess dataAccess = new DataAccess();
            dataAccess.Delete(id);

            List<User> user =  dataAccess.FetchAllUser();

            return View("Index", user);
        }

        //Store : User
        public IActionResult Create()
        {
            return View("CreateForm");
        }
        //Edit
        public IActionResult EditUser(int id)
        {
            DataAccess dataAccess = new DataAccess();
            User user = dataAccess.FetchOneUser(id);
            return View("Edit", user);
        }


        [HttpPost]
        public IActionResult CreateUser(User user)
        {
            DataAccess dataAccess = new DataAccess();
            dataAccess.CreateOrUpdate(user);
            Index();
            return View("Index");
        }
    }
}

Meeting Minutes/Meeting Minutes/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Meeting Minutes/Meeting Minutes/Views/Meeting/Index.cshtml
@model IEnumerable<Meeting_Minutes.Models.Meeting>

@{
    ViewData["Title"] = "Index";

    Layout = "~/Views/Shared/_Layout.cshtml";



}

<h1>Meetings</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.meetingNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.meetingDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MeetingTypeId)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.meetingNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.meetingDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MeetingTypeId)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.meetingID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.meetingID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.meetingID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Meeting Minutes/Meeting Minutes/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Meeting_Minutes</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Meeting_Minutes.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Meeting_Minutes</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Meeting" asp-action="index">Meeting</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">User</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Meeting_Minutes - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Meeting Minutes/Meeting Minutes/Views/User/CreateForm.cshtml
@model Meeting_Minutes.Models.User
       

@{
    ViewData["Title"] = "CreateForm";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>CreateForm</h1>

<h4>User</h4>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateUser">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="UserName" class=" control-label"></label>
                <input asp-for="UserName" class="form-control" />
                <span asp-validation-for="UserName" class="text-danger"></span>
            </div>
           
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Meeting Minutes/Meeting Minutes/Views/User/Edit.cshtml
@model Meeting_Minutes.Models.User


@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>User</h4>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateUser">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="UserName" class=" control-label"></label>
                <input asp-for="UserName" class="form-control" />
                <span asp-validation-for="UserName" class="text-danger"></span>
            </div>
            <input type="hidden" name="UserId" value="@Model.UserId" />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Meeting Minutes/Meeting Minutes/Views/User/Index.cshtml
@model IEnumerable<Meeting_Minutes.Models.User>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Users</h1>

<p>
    <a asp-action="Create">Create New User</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                User name
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.UserName)
            </td>
            <td>
                <a asp-action="EditUser" asp-route-id="@item.UserId">Edit</a> |
                <a asp-action="DeleteUser" asp-route-id="@item.UserId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>